on:
  pull_request:
    branches:
      - fe-deploy-test
    paths:
      - "frontend/**"

jobs:
  deploy:
    name: front-deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: checkout source code
        uses: actions/checkout@v2

      - name: SSH-deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          port: ${{ secrets.REMOTE_PORT }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          script: |
            cd /repository
            mkdir hello
