on:
  pull_request:
    branches:
      - fe-deploy-test
    paths:
      - "frontend/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: dorny/paths-filter@v2.11.1
        id: changes
        with:
          filters: |
            frontend:
              - 'frontend/**'

      - name: deploy front
        if: steps.changes.outputs.frontend == 'true'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          port: ${{ secrets.REMOTE_PORT }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          script: |
            cd /home/ubuntu
            git pull origin fe-deploy-test
